from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.takeoff_agent import Takeoff_DDPG
from quad_controller_rl.agents.hover_agent import Hover_DDPG